<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Empresa [
   <!ELEMENT Empresa (Empleado*)>
   <!ELEMENT Empleado (Apellido+, Nombre, (Email | Telefono), Direccion)>
   <!ATTLIST Empleado NumEmpleado CDATA #IMPLIED>
   <!ELEMENT Apellido (#PCDATA)>
   <!ELEMENT Nombre (#PCDATA)>
   <!ELEMENT Email (#PCDATA)>
   <!ELEMENT Telefono (#PCDATA)>
   <!ELEMENT Direccion (#PCDATA)>
   <!ATTLIST Direccion Calle CDATA #REQUIRED>
   <!ATTLIST Direccion Ciudad CDATA #IMPLIED>
   <!ATTLIST Direccion CP CDATA #REQUIRED>
]>

<Empresa>
    <Empleado NumEmpleado="1234567890">
      <Apellido>Perez</Apellido>
      <Apellido>Garcia</Apellido>
      <Nombre>Juan</Nombre>
      <!--<NumEmpleado>1234567890</NumEmpleado>-->
      <Telefono>666 555 444</Telefono>
      <Direccion Calle="Carrer de Pau Claris, 121" Ciudad="Barcelona" CP="08009">
        <!--<Calle>Carrer de Pau Claris, 121</Calle>
        <Ciudad>Barcelona</Ciudad>
        <CP>08009</CP>-->
      </Direccion>  
    </Empleado>
    <Empleado NumEmpleado="0987654321">
        <Apellido>Gonzalo</Apellido>
        <Apellido>Perez</Apellido>
        <Nombre>Luis</Nombre>
        <!--<NumEmpleado>0987654321</NumEmpleado>-->
        <Telefono>699 777 666</Telefono>
        <Direccion Calle="Carrer de Pau Claris, 231" Ciudad="Barcelona" CP="08042"/>
          <!--<Calle>Carrer de Pau Claris, 231</Calle>
          <Ciudad>Barcelona</Ciudad>
          <CP>08042</CP>-->
    </Empleado>
</Empresa>  